Lesson5
MadinaShatayeva7/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-10 23:01 UTC by MadinaShatayeva7

Привет, Андрей! Вроде все работает кроме того что, в открытии модалки нужно переписать тройное равно === вместо ==) 
а до него оно не разрешало пушить) а так с тройным равно оно не открывает модалку

2021-10-11 04:38 UTC, wizzout commented
> Привет, Андрей! Вроде все работает кроме того что, в открытии модалки нужно переписать тройное равно === вместо ==) а до него оно не разрешало пушить) а так с тройным равно оно не открывает модалку

![Screen Shot 2021-10-11 at 10 28 11](https://user-images.githubusercontent.com/22858436/136734048-1d7ee286-be4c-4878-8174-a3c01d1853a4.png)

2021-10-11 04:56 UTC, wizzout requested changes
Сделай так чтобы все заработало, разберись почему == работает а === нет оптимизируй код

дедлайн 12.00 12 октября

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +const clothes = [
Попробуй вынести в отдельный файл все моки - и тут просто импортировать - чтобы чище стало

не обязательно

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +const makeProductCard = (img, alt, title, price, badge, size, id) => ` <div data-id="${id}" class="content__product" >
а этот пробел нужен?

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +const renderCard = (item) => {
вроде название говорит что отрендерится одна карточка - а по коду тут все происходит и сортировка (подскажи, нужно ли делать каждый раз?) и отрисовка всех! карточек а аргумент item вообще игнорится. 

Функция должна в идеале работать только с входными данными. Не всегда это реально сделать - но хотя бы надо стараться минимизировать ее отвественность — тут должна наполнится и добавится одна карточка. может еще слушатель клика проставляться

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +        wrapper.innerHTML += cardHtml;
а нужен ли тебе wrapper?

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +    all.forEach((item) => {
а если поискать другие, более полезные методы перебора массива? ;) такое решение не пойдет

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +    document.querySelector('.scores__left-title').textContent = info.price;
а откуда уверенность что info определено?

2021-10-11 04:56 UTC, wizzout commented on src/js/main.js
> +document.querySelectorAll('[data-id]').forEach((item) => {
ты один раз слушаешь клик - при инициализации страницы. но потом ты заменяешь карточки и больше никто не реагирует на клик

2021-10-11 17:05 UTC, MadinaShatayeva7 commented on src/js/main.js
> +const clothes = [
> Попробуй вынести в отдельный файл все моки - и тут просто импортировать - чтобы чище стало
> 
> не обязательно

вынесла=)

2021-10-11 17:07 UTC, MadinaShatayeva7 commented on src/js/main.js
> +const makeProductCard = (img, alt, title, price, badge, size, id) => ` <div data-id="${id}" class="content__product" >
> а этот пробел нужен?

если правильно понимаю ты про пустую строку между ними) убрала!

2021-10-12 03:36 UTC, wizzout commented on src/js/main.js
> +const makeProductCard = (img, alt, title, price, badge, size, id) => ` <div data-id="${id}" class="content__product" >
нет, я про пробел в стринге перед div

2021-10-12 04:09 UTC, wizzout approved these changes
Жаль что не получилось решить проблемы, надебсь советы помогут и ты еще найдешь силы доработать код. Но в отдельно уже, а этот ПР можно мержить;

2021-10-12 04:09 UTC, wizzout commented on src/js/main.js
> +document.querySelectorAll('div[data-id]').forEach((item) => {
то что ты добавила div ничего не меняет. Результат функции не реактивен и при удалении элемента и добавлении нового слушатель не преподвяжется. 

Тебе нужно слушатели привязывать внутри цикла добавления карточки. только немного переделать чтобы у тебя была не просто строка а DOM нода - тогда в ней можно будет найти кнопку  добавить ей слушателя

2021-10-12 04:09 UTC, wizzout commented on src/js/main.js
>          openModal(item.dataset.id);
все что хранится в dataset является строкой (это же просто атрибут элемента) и вот тут начинаются твои проблемы 

ты условано вызываешь метод openModal с аргументом `'1'` а в массиве объектов у тебя поле id в виде чисел `1`.

и при поиске у тебя происходит сравнение чтобы `1 === '1'` но при строгом сравнении это будет false и не будет найдено ни одного объекта с данными

2021-10-12 04:09 UTC, wizzout commented on src/js/main.js
>          openModal(item.dataset.id);
Как вариант приводить данные в один тип - например `openModal(Number(item.dataset.id));`

2021-10-12 04:09 UTC, wizzout commented on src/js/main.js
>      document.querySelector('.modal-main-wrap').classList.add('modal-main-wrap--active');
тут напишу, но комментарий на строчки вверх идет вместо all.forEach стоит сделать 
```javascript
const info = all.find(item => item.id === id);
```

код практически тот же, токо он прекратит обход цикла как только найдет подходящий элемент

Ну и всегда котда у тебя неявное присвание и поиск стоит делать проверку

```javascript
if (info === undefined) { 
  return; 
}
```

2021-10-19 12:50 UTC, merged